# Generated by Django 2.0.2 on 2018-02-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Adult')),
            ],
        ),
    ]
