# Generated by Django 2.0.2 on 2018-02-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Child')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Program')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RegistrationType'),
        ),
    ]
