# Generated by Django 2.0.2 on 2018-02-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180225_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration_type',
        ),
        migrations.AddField(
            model_name='registration',
            name='is_wait_list',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RegistrationType',
        ),
    ]
