# Generated by Django 2.0.2 on 2018-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_program_is_teen'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='graphic',
            field=models.ImageField(default='graphic.jpg', upload_to='graphics'),
        ),
    ]
