# Generated by Django 2.0.2 on 2018-04-02 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_adult_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '123-456-7890'.", regex='^d{3}\\-?d{3}-?d{4}$')]),
        ),
    ]
