# Generated by Django 2.0.2 on 2018-04-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180416_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='confirmation_number',
            field=models.CharField(default='b3b3035e', max_length=8),
        ),
    ]
