# Generated by Django 2.0.2 on 2018-04-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_adult_confirmation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='photo_release',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
