# Generated by Django 2.0.2 on 2018-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_adult_photo_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adult',
            name='photo_release',
        ),
        migrations.AddField(
            model_name='child',
            name='photo_release',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
