# Generated by Django 2.0.2 on 2018-04-30 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180426_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='time_end',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
